# SPDX-License-Identifier: Apache-2.0

linters:
  enable:
  - asciicheck
  - unused
  - depguard
  - errcheck
  - errorlint
  - forbidigo
  - gofmt
  - goimports
  - gosec
  - gocritic
  - importas
  - prealloc
  - revive
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - whitespace
output:
  uniq-by-line: false
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # TODO: review the sha1 and other cryptographic primitive
  exclude:
    - G401
    - G501
    - G505
run:
  issues-exit-code: 1
  timeout: 10m
